Sorting and Searching

In [ ]:
def my_string(x):
 return x[::-1]
s= my_string("1234abcd")
print("My reverse string is: ",s)

My reverse string is:  dcba4321


In [ ]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)
n=int(input("Input a number to compute the factiorial : "))
print(factorial(n))

Input a number to compute the factiorial : 5
120


In [ ]:
def unique_list(numbers):
    unique = []
    for item in numbers :
        if item not in unique:
            unique.append(item)
    return unique

print(unique_list([1, 2, 3, 1, 2]))

[1, 2, 3]


In [2]:
import numpy as np
x = np.array([44,21,56,35,60,5])
np.sort(x)

array([ 5, 21, 35, 44, 56, 60])

In [3]:
array = np.arange(12).reshape(3, 4)
print("INPUT ARRAY: ", array)
print("\nMax element : ", np.argmax(array))
print(("\nIndices of Max element : ", np.argmax(array, axis=0)))
print(("\nIndices of Max element : ", np.argmax(array, axis=1)))


INPUT ARRAY:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Max element :  11
('\nIndices of Max element : ', array([2, 2, 2, 2]))
('\nIndices of Max element : ', array([3, 3, 3]))


In [4]:
array = np.arange(8)
print("INPUT ARRAY : \n", array)
print("\nIndices of min element : ", np.argmin(array, axis=0))

INPUT ARRAY : 
 [0 1 2 3 4 5 6 7]

Indices of min element :  0


In [5]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)
