Statistical and File Operations

In [ ]:
import numpy as np

In [ ]:
np.add(3.5,5.7)

9.2

In [ ]:
np.subtract(9.0,5)

4.0

In [ ]:
np.multiply(8,4)

32

In [ ]:
np.divide(99,77)

1.2857142857142858

In [ ]:
a =np.array([[9,13,5,2],[1,11,7,6],[3,7,4,1],[6,0,7,10]])

In [ ]:
np.max(a,0)

array([ 9, 13,  7, 10])

In [ ]:
np.max(a,1)

array([13, 11,  7, 10])

In [ ]:
np.min(a,0)

array([1, 0, 4, 1])

In [ ]:
np.min(a,1)

array([2, 1, 1, 0])

In [ ]:
np.sum(a,axis=0)

array([19, 31, 23, 19])

In [ ]:
np.sum(a,axis=1)

array([29, 25, 15, 23])

In [ ]:
b = [10,20,30,40,50,60,70,80,90,100]

In [ ]:
np.mean(b)

55.0

In [ ]:
np.median(b)

55.0

In [ ]:
np.std(b)

28.722813232690143

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('student_data.csv')
df

admit  gre   gpa  rank
0        0  380  3.61     3
1        1  660  3.67     3
2        1  800  4.00     1
3        1  640  3.19     4
4        0  520  2.93     4
..     ...  ...   ...   ...
395      0  620  4.00     2
396      0  560  3.04     3
397      0  460  2.63     2
398      0  700  3.65     2
399      0  600  3.89     3

[400 rows x 4 columns]

In [ ]:
df1 =pd.read_csv('subject_marks.txt')
df1

#Roll_no Subject1 Subject2 Subject3
0     1           78      87        89
1     2           67      77        92
2     3           56      77        94
3     4           78      87        89
4     5           78      87        89
5     6           67      77        92
6     7           56      77        94
7     8           78      87        89
8     9           78      87        89
9    11           67      77        92
10   12           56      77        94
11   13           78      87        89

In [ ]:
data = pd.read_csv('bank_data.csv')

In [ ]:
data

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [ ]:
d1 = data.iloc[:,[3,4,6,7,8,13]]
d1

CreditScore Geography  Age  Tenure    Balance  Exited
0             619    France   42       2       0.00       1
1             608     Spain   41       1   83807.86       0
2             502    France   42       8  159660.80       1
3             699    France   39       1       0.00       0
4             850     Spain   43       2  125510.82       0
...           ...       ...  ...     ...        ...     ...
9995          771    France   39       5       0.00       0
9996          516    France   35      10   57369.61       0
9997          709    France   36       7       0.00       1
9998          772   Germany   42       3   75075.31       1
9999          792    France   28       4  130142.79       0

[10000 rows x 6 columns]

In [ ]:
d1.isnull().sum()

CreditScore    0
Geography      0
Age            0
Tenure         0
Balance        0
Exited         0
dtype: int64

In [ ]:
d1.replace(0,np.nan)

CreditScore Geography  Age  Tenure    Balance  Exited
0             619    France   42     2.0        NaN     1.0
1             608     Spain   41     1.0   83807.86     NaN
2             502    France   42     8.0  159660.80     1.0
3             699    France   39     1.0        NaN     NaN
4             850     Spain   43     2.0  125510.82     NaN
...           ...       ...  ...     ...        ...     ...
9995          771    France   39     5.0        NaN     NaN
9996          516    France   35    10.0   57369.61     NaN
9997          709    France   36     7.0        NaN     1.0
9998          772   Germany   42     3.0   75075.31     1.0
9999          792    France   28     4.0  130142.79     NaN

[10000 rows x 6 columns]

In [ ]:
d1.dropna()

CreditScore Geography  Age  Tenure    Balance  Exited
0             619    France   42       2       0.00       1
1             608     Spain   41       1   83807.86       0
2             502    France   42       8  159660.80       1
3             699    France   39       1       0.00       0
4             850     Spain   43       2  125510.82       0
...           ...       ...  ...     ...        ...     ...
9995          771    France   39       5       0.00       0
9996          516    France   35      10   57369.61       0
9997          709    France   36       7       0.00       1
9998          772   Germany   42       3   75075.31       1
9999          792    France   28       4  130142.79       0

[10000 rows x 6 columns]

In [ ]:
d1.replace(0," ")

CreditScore Geography  Age Tenure  Balance Exited
0             619    France   42      2               1
1             608     Spain   41      1  83807.9       
2             502    France   42      8   159661      1
3             699    France   39      1                
4             850     Spain   43      2   125511       
...           ...       ...  ...    ...      ...    ...
9995          771    France   39      5                
9996          516    France   35     10  57369.6       
9997          709    France   36      7               1
9998          772   Germany   42      3  75075.3      1
9999          792    France   28      4   130143       

[10000 rows x 6 columns]

In [ ]:
d2 = pd.read_csv('weather.csv')

In [ ]:
d2

day     city  temperature  humidity
0    2020-01-01   France           42        65
1    2020-01-02    Spain           41        61
2    2020-01-03   France           42        60
3    2020-01-04    Spain           41        40
4    2020-01-05   France           41        67
..          ...      ...          ...       ...
844  2022-04-24  Germany           44        67
845  2022-04-25    Spain           49        80
846  2022-04-26   France           21        84
847  2022-04-27   France           42        65
848  2022-04-28  Germany           51        61

[849 rows x 4 columns]

In [ ]:
d3 = d2[['city','temperature','humidity']]

In [ ]:
d3

city  temperature  humidity
0     France           42        65
1      Spain           41        61
2     France           42        60
3      Spain           41        40
4     France           41        67
..       ...          ...       ...
844  Germany           44        67
845    Spain           49        80
846   France           21        84
847   France           42        65
848  Germany           51        61

[849 rows x 3 columns]